export const INITIAL_FORM_STATE = {
  srNo: '',
  date: new Date().toISOString().split('T')[0],
  location: '',
  position: '',
  fls: '',
  name: '',
  contact: '',
  email: '',
  companyName: '',
  experience: '',
  ctc: '',
  expectedCtc: '',
  noticePeriod: '',
  status: 'Applied',
  client: '',
  spoc: '',
  source: '',
  resume: null,
  callBackDate: '',
  countryCode: '+91',
  skills: '',
  remark: '',
};
