/** Built-in starters — aligned with common ATS / BFSI roles; not stored in DB */
export const STARTER_TEMPLATES = [
  {
    id: 'starter-rm-platinum',
    role: 'RELATIONSHIP MANAGER PLATINUM',
    experience: '2-5 YEARS',
    location: 'DELHI, NOIDA, GURUGRAM',
    locations: ['DELHI', 'NOIDA', 'GURUGRAM'],
    ctc: '6L-10L',
    grade: 'ASSISTANT MANAGER',
    industry: 'LIFE INSURANCE',
    employmentType: 'full_time',
    skills: ['RELATIONSHIP MANAGEMENT', 'LIFE INSURANCE', 'SALES', 'PORTFOLIO'],
    description:
      'Drive platinum segment acquisition and retention. Own end-to-end relationship management, cross-sell insurance solutions, and deliver against branch targets.',
    summary: 'We are hiring a Relationship Manager for the platinum segment to grow and nurture high-value customer relationships.',
    isStarter: true,
  },
  {
    id: 'starter-abm',
    role: 'ASSISTANT BRANCH MANAGER',
    experience: '3-6 YEARS',
    location: 'MUMBAI, PUNE',
    locations: ['MUMBAI', 'PUNE'],
    ctc: '8L-14L',
    grade: 'ASSISTANT BRANCH HEAD',
    industry: 'LIFE INSURANCE',
    employmentType: 'full_time',
    skills: ['TEAM LEADERSHIP', 'BRANCH OPERATIONS', 'LIFE INSURANCE', 'TARGET ACHIEVEMENT'],
    description:
      'Support branch leadership on sales, operations, and people management. Coach advisors and ensure compliance with process and quality standards.',
    summary: 'Assistant Branch Manager to support sales leadership and day-to-day branch operations.',
    isStarter: true,
  },
  {
    id: 'starter-agency-dev',
    role: 'AGENCY DEVELOPMENT MANAGER',
    experience: '4-8 YEARS',
    location: 'HYDERABAD, BANGALORE, CHENNAI',
    locations: ['HYDERABAD', 'BANGALORE', 'CHENNAI'],
    ctc: '10L-16L',
    grade: 'MANAGER',
    industry: 'LIFE INSURANCE',
    employmentType: 'full_time',
    skills: ['AGENCY RECRUITMENT', 'TRAINING', 'LIFE INSURANCE', 'CHANNEL DEVELOPMENT'],
    description:
      'Build and scale the agency channel through recruitment, activation, and ongoing performance coaching of advisors.',
    summary: 'Agency Development Manager responsible for growing and enabling the agency distribution channel.',
    isStarter: true,
  },
  {
    id: 'starter-health-rm',
    role: 'HEALTH INSURANCE RELATIONSHIP MANAGER',
    experience: '1-4 YEARS',
    location: 'DELHI, MEERUT, NOIDA',
    locations: ['DELHI', 'MEERUT', 'NOIDA'],
    ctc: '4L-8L',
    grade: 'EXECUTIVE',
    industry: 'HEALTH INSURANCE',
    employmentType: 'full_time',
    skills: ['HEALTH INSURANCE', 'CUSTOMER ACQUISITION', 'CROSS SELL', 'CRM'],
    description:
      'Acquire and service health insurance customers, explain product benefits clearly, and meet monthly activation and renewal goals.',
    summary: 'Relationship Manager focused on health insurance acquisition and customer servicing.',
    isStarter: true,
  },
  {
    id: 'starter-bfsi-sales',
    role: 'BFSI SALES OFFICER',
    experience: '1-3 YEARS',
    location: 'CHENNAI',
    locations: ['CHENNAI'],
    ctc: '3L-6L',
    grade: 'EXECUTIVE',
    industry: 'BFSI',
    employmentType: 'full_time',
    skills: ['BANKING', 'SALES', 'CUSTOMER SERVICE', 'KYC'],
    description:
      'Generate leads, convert walk-ins and referrals, and support customers through onboarding for banking and insurance products.',
    summary: 'Front-line BFSI sales role focused on lead conversion and customer onboarding.',
    isStarter: true,
  },
  {
    id: 'starter-fullstack',
    role: 'FULL STACK DEVELOPER',
    experience: '3-5 YEARS',
    location: 'BANGALORE / HYBRID',
    locations: ['BANGALORE'],
    ctc: '12L-18L',
    grade: 'SENIOR EXECUTIVE',
    industry: 'IT / SOFTWARE',
    employmentType: 'full_time',
    skills: ['REACT', 'NODE.JS', 'MONGODB', 'EXPRESS'],
    description:
      'Build and maintain scalable web applications end-to-end. Own API design, frontend architecture, and deployment collaboration with DevOps.',
    summary: 'Full Stack Developer to own features across frontend and backend services.',
    isStarter: true,
  },
];

export const emptyForm = {
  role: '',
  experience: '',
  location: '',
  ctc: '',
  skills: '',
  description: '',
};

export const mapJobToTemplate = (job) => ({
  id: job._id,
  _id: job._id,
  role: job.role || job.title || 'Untitled',
  experience: job.experience || '',
  location: job.location || '',
  locations: job.locations || [],
  ctc: job.ctc || '',
  grade: job.grade || '',
  clientName: job.clientName || '',
  industry: job.industry || '',
  employmentType: job.employmentType || 'full_time',
  summary: job.summary || '',
  description: job.description || job.summary || '',
  skills: job.skills || [],
  isStarter: false,
});
